### PR TITLE
User recommendation

### PR DESCRIPTION
**Pull request by nmtri2810**
## Related Tickets
- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70645)

## WHAT
- Tạo recommendation book cho user

## HOW
- Sử dụng carousel xuất view cho user

## Evidence (Screenshot or Video)
image

## Notes (Kiến thức tìm hiểu thêm)
- Metaprogramming

### CODE REVIEW

**Comment by nmtri2810** [comment]
ready

**Comment by nmtri2810** [comment]
ready

**Comment by nmtri2810** [comment]
ready

**Comment by nmtri2810** [comment]
ready

**Review by anlvq-1058 — APPROVED** [review]
merged

**Pull request merged**
